name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Install dependencies
        run: go mod tidy

      - name: Build the Go binary
        run: GOOS=linux GOARCH=arm64 go build -o bootstrap cmd/main.go

      - name: Zip the binary
        run: zip function.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name go-lambda-test-echo --zip-file fileb://function.zip